version: '3.7'
services:
  zoo:
    image: gncorp/zoo:1.1.0-SNAPSHOT
    ports:
      - 9070:8081
    depends_on:
      - db
      - keycloak
    networks:
      - zoonetwork
      
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - zoonetwork
      
  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8080:8080
    networks:
      - zoonetwork
      
volumes:
  my-db:
  
networks:
  zoonetwork:
    driver: bridge